default_platform(:android)

platform :android do
  desc "Build a release APK"
  lane :build_apk do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
    # You can add more actions here, such as signing the APK if needed
  end
end
