lane :beta do
  increment_build_number
  gradle(task: "assembleRelease")
  bundle_release(output_directory: "app/build/outputs/bundle/release")
  upload_to_play_store(
    track: 'beta',
    release_name: "Beta release #{build_number}"
  )
end
