name: Android APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Specify the Java distribution
        java-version: '11'

    - name: Install Ruby and Bundler
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby-full
        gem install bundler
        bundle install

    - name: Cache Fastlane gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: bundle-${{ runner.os }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-${{ runner.os }}

    - name: Build APK with Fastlane
      run: bundle exec fastlane android build_apk

    - name: Upload APK to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
