name: Android APK Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '3.0' # or the version your project requires

    - name: Install dependencies with Bundler
      run: |
        gem install bundler
        bundle config set --local path 'vendor/bundle'
        bundle install

    - name: Build APK with Fastlane 
      run: bundle exec fastlane android build_apk

    - name: Upload APK to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
