name: Build APK with Fastlane

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - name: Install dependencies with Bundler
      run: bundle install
      working-directory: ./ # Adjust this path to where Gemfile is located

    - name: List files in working directory
      run: ls -la ./ # Adjust this path to verify Fastlane installation

    - name: Check Fastlane version
      run: bundle exec fastlane --version
      working-directory: ./ # Ensure this path matches the Gemfile location

    - name: Build APK with Fastlane
      run: bundle exec fastlane android build_apk
      working-directory: ./  # Ensure this path matches the Gemfile location

    - name: Upload APK to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk # Adjust this path if different
