name: Build APK with Fastlane

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # Using Temurin distribution for OpenJDK
        java-version: '11'

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' # Ruby version used by Fastlane
        bundler-cache: true # Caches installed gems

    - name: Install dependencies with Bundler
      run: bundle install

    - name: Build APK with Fastlane
      run: bundle exec fastlane android build_apk # Replace `build_apk` with your Fastlane lane

    - name: Upload APK to GitHub Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk # Adjust this path if different
